repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/srstevenson/nb-clean
    rev: 2.4.0
    hooks:
      - id: nb-clean
        stages: [commit] # When the hook will be run
        args:
          - --remove-empty-cells
          - --preserve-cell-metadata
          - collapsed
          - scrolled
          - deletable
          - editable
          - format
          - name
          - tags
          - jupyter
          - execution
          - --
        exclude: ^(.*\/)*docs\/.*$

  # Run flake8
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      # Run unit test on mlcc library
      - id: flake8
        args: ["--append-config=./linter/.flake8", "--output=_flake8_output"]

  # Run black
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      # Run unit test on mlcc library
      - id: black
        args: ["--config", "./linter/.black"]
        exclude: "(.*\\/)*(__init__\\.py|template\\/.*|template\\.py)"
